=encoding utf8

=head1 TITLE

Synopsis 29: Functions

=head1 AUTHOR

Rod Adams <rod@rodadams.net>

=head1 VERSION

  Maintainer: Rod Adams <rod@rodadams.net>

=head1 Placeholder

This pod is just a placeholder for the draft of Synopsis 29 that
Rod Adams is currently building and maintaining, until we feel that
the draft has matured sufficiently to warrant inclusion with the
other Apocalypses and Synopses.

Until they appear here, the latest drafts are available at

    http://www.rodadams.net/Perl/S29.pod
    http://www.rodadams.net/Perl/S29.html


