=encoding utf8

=head1 TITLE

Synopsis 17: Threads

=head1 AUTHOR

=head1 VERSION

  Maintainer: unclaimed
  Date: 13 Jun 2005
  Last Modified: 13 Jun 2005
  Number: 0
  Version: 1

=head1 Overview

This synopsis is currently only a framework to outline what information
needs to be covered.

=head1 Implementation of Threads in Perl

=head1 Coroutines

=head1 Universal Asynchronous I/O

=head1 Timers and Timeouts

=for vim:set expandtab sw=4:
